version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: node-backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "your_mongodb_atlas_connection_string"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/src/app
