version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: node-backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
