version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: node-backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb+srv://huybui:huybui123@cluster0.atjqmys.mongodb.net/photoapp?retryWrites=true&w=majority&appName=Cluster0"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/src/app
